# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('goods', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.Address')),
            ],
            options={
                'db_table': 'back_address',
            },
            bases=('user.address',),
        ),
        migrations.CreateModel(
            name='BackGoods',
            fields=[
                ('goods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.Goods')),
            ],
            options={
                'db_table': 'back_goods',
            },
            bases=('goods.goods',),
        ),
        migrations.CreateModel(
            name='BackOrderGoods',
            fields=[
                ('ordergoods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.OrderGoods')),
            ],
            options={
                'db_table': 'back_order_goods',
            },
            bases=('order.ordergoods',),
        ),
        migrations.CreateModel(
            name='BackOrderInfo',
            fields=[
                ('orderinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.OrderInfo')),
            ],
            options={
                'db_table': 'back_order_info',
            },
            bases=('order.orderinfo',),
        ),
        migrations.CreateModel(
            name='BackUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.User')),
            ],
            options={
                'db_table': 'back_users',
            },
            bases=('user.user',),
        ),
    ]
